# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca33b8d3115242af114999a1a8590356c3b59b48cbec5333234ec10547f38b441e89a2ad486560a3bc194782e3151b120b342312a3eba7ad5a2c4dfb45514230

test:
  secret_key_base: 314b4f8da47b5efec6ae064774a55b50a830ca79111f36c96938c0dac6302246c90944b760eba36b692152cb13ac5394941a31b67d5ed5ceca5a8c81a6c98f51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
